name: Permissions
main: com.nijikokun.bukkit.Permissions.Permissions
version: 3.0a
author: TheNo1Yeti
website: www.theyeticave.net
description: >
             Provides a Permissions framework for use with Bukkit Plugins
commands:
  permissions:
    aliases: [perms, pr]
    description: Provides access to Permissions commands and information.
    usage: |
           /<command>
           Example: /<command> | Displays Permissions Info
           Example: /<command> -reload all | Reloads the default world configuration
           Example: /<command> -reload [world] | Reloads the [world] configuration file
